spring:
  application:
    name: spektr

endpoint-jars:
  dir: ${ENDPOINT_JARS_DIR:./endpoint-jars}

spektr:
  additional-configs: ${CONFIGS_DIR:optional:file:./Users/violabs/Projects/spektr/app}
  rest:
    enabled: ${SPEKTR_REST_ENABLED:true}
  soap:
    enabled: ${SPEKTR_SOAP_ENABLED:true}