spring:
  application:
    name: spektr

endpoint-jars:
  dir: ${ENDPOINT_JARS_DIR:./endpoint-jars}

spektr:
  rest:
    enabled: ${SPEKTR_REST_ENABLED:true}
  soap:
    enabled: ${SPEKTR_SOAP_ENABLED:true}